### ISSUE TITLE
Where is Code Fusion layer implemented?

### ISSUE THREAD

**Issue by reachsumit** [Jyonn/Cove#1]
Thank you for sharing your work. It is a very interesting approach.

The paper mentions applying a Code Fusion layer that employs average pooling operation on the quantized vectors. However, the current Cove implementation seems to only return the quantized output object.

Also, could you please clarify how (if) the training/inference time paths would be different? Thank you!

**Comment by Jyonn** [comment]
Hi, thanks for your attention! 

Our code fusion operation is implemented in Line 93-95 in cove.py. You can have a look at the common.py, and Average pooling (mean) operation is written inside the CoveQuantization class.

For your second question, there would be no difference during training or inference regarding to what you said “time path”. But you should set with_loss to True during training, and it can be False during inference.
