### ISSUE TITLE
Questions about hyperparameters

### ISSUE THREAD

**Issue by striderdu** [Jyonn/Cove#2]
Hi,  Jyonn @Jyonn 

Thanks for your awesome work!

Could you introduce some details about **vocab_size** and **entries** in class Cage? I try to assign specific entries, which indicate different k values of different categories in Equation(1) on your paper. But according to the released code, it only seems to be related to **vocab_size**.

**Comment by Jyonn** [comment]
Hi, thanks for your attention to our work!

`vocab_size` denotes the number of items, which is used for sequential recommendation task (i.e., list completion task). CAGE module will prepare several classification modules according to the additional category tree classification task in Sec 4.2.

**Comment by striderdu** [comment]
Thanks for your reply!

So how do I need to set the `vocab_size` if I want to use the CAGE for CTR tasks. Is it the number of items in the CTR dataset? When I set `entries` to [100, 10], I expect the size of the two codebooks to be [100,10] respectively, but the actual size of the two codebooks obtained is related to the `vocab_size`.

**Comment by Jyonn** [comment]
Hi, in this case, please remove the `set_cluster_size` method, which is an automatic function to determine cluster sizes based on vocabulary size.

**Comment by striderdu** [comment]
OK. I got it. Thanks again for your patient reply!
